apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/L3xu5/minecraft-yc-devops.git
    targetRevision: main
    path: k8s/platform
    directory:
      include: '{namespace.yaml,fluent-bit.yaml,github-actions-rbac.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
