apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-secrets
  namespace: minecraft
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: yandex-lockbox
    kind: SecretStore
  target:
    name: minecraft-secrets
    creationPolicy: Owner
  data:
    - secretKey: rcon-password
      remoteRef:
        key: "${LOCKBOX_SECRET_ID}"
        property: rcon-password
    - secretKey: s3-access-key
      remoteRef:
        key: "${LOCKBOX_SECRET_ID}"
        property: s3-access-key
    - secretKey: s3-secret-key
      remoteRef:
        key: "${LOCKBOX_SECRET_ID}"
        property: s3-secret-key
